# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverchat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverchat.proto',
  package='serverchat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10serverchat.proto\x12\nserverchat\"\x07\n\x05\x45mpty\"%\n\x11\x43onnectionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"*\n\x14\x44isconnectionRequest\x12\x12\n\nuser_token\x18\x01 \x01(\t\"L\n\x12\x43onnectionResponse\x12\x12\n\nuser_token\x18\x01 \x01(\t\x12\"\n\x06status\x18\x02 \x01(\x0b\x32\x12.serverchat.Status\".\n\x06Status\x12\r\n\x05is_ok\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"+\n\x07Message\x12\x12\n\nuser_token\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x9c\x01\n\x06\x41\x63tion\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x32\n\x0b\x61\x63tion_type\x18\x02 \x01(\x0e\x32\x1d.serverchat.Action.ActionType\x12\x0f\n\x07payload\x18\x03 \x01(\t\";\n\nActionType\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x0e\n\nDISCONNECT\x10\x01\x12\x10\n\x0cSEND_MESSAGE\x10\x02\x32\x97\x02\n\nServerChat\x12J\n\x07\x63onnect\x12\x1d.serverchat.ConnectionRequest\x1a\x1e.serverchat.ConnectionResponse\"\x00\x12\x44\n\ndisconnect\x12 .serverchat.DisconnectionRequest\x1a\x12.serverchat.Status\"\x00\x12\x39\n\x0csend_message\x12\x13.serverchat.Message\x1a\x12.serverchat.Status\"\x00\x12<\n\x0fget_chat_stream\x12\x11.serverchat.Empty\x1a\x12.serverchat.Action\"\x00\x30\x01\x62\x06proto3'
)



_ACTION_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='serverchat.Action.ActionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEND_MESSAGE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=393,
  serialized_end=452,
)
_sym_db.RegisterEnumDescriptor(_ACTION_ACTIONTYPE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='serverchat.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=39,
)


_CONNECTIONREQUEST = _descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='serverchat.ConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='serverchat.ConnectionRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=78,
)


_DISCONNECTIONREQUEST = _descriptor.Descriptor(
  name='DisconnectionRequest',
  full_name='serverchat.DisconnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_token', full_name='serverchat.DisconnectionRequest.user_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=122,
)


_CONNECTIONRESPONSE = _descriptor.Descriptor(
  name='ConnectionResponse',
  full_name='serverchat.ConnectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_token', full_name='serverchat.ConnectionResponse.user_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='serverchat.ConnectionResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=200,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='serverchat.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_ok', full_name='serverchat.Status.is_ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='serverchat.Status.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=248,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='serverchat.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_token', full_name='serverchat.Message.user_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='serverchat.Message.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=293,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='serverchat.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='serverchat.Action.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_type', full_name='serverchat.Action.action_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='serverchat.Action.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTION_ACTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=452,
)

_CONNECTIONRESPONSE.fields_by_name['status'].message_type = _STATUS
_ACTION.fields_by_name['action_type'].enum_type = _ACTION_ACTIONTYPE
_ACTION_ACTIONTYPE.containing_type = _ACTION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ConnectionRequest'] = _CONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['DisconnectionRequest'] = _DISCONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['ConnectionResponse'] = _CONNECTIONRESPONSE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'serverchat_pb2'
  # @@protoc_insertion_point(class_scope:serverchat.Empty)
  })
_sym_db.RegisterMessage(Empty)

ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREQUEST,
  '__module__' : 'serverchat_pb2'
  # @@protoc_insertion_point(class_scope:serverchat.ConnectionRequest)
  })
_sym_db.RegisterMessage(ConnectionRequest)

DisconnectionRequest = _reflection.GeneratedProtocolMessageType('DisconnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTIONREQUEST,
  '__module__' : 'serverchat_pb2'
  # @@protoc_insertion_point(class_scope:serverchat.DisconnectionRequest)
  })
_sym_db.RegisterMessage(DisconnectionRequest)

ConnectionResponse = _reflection.GeneratedProtocolMessageType('ConnectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONRESPONSE,
  '__module__' : 'serverchat_pb2'
  # @@protoc_insertion_point(class_scope:serverchat.ConnectionResponse)
  })
_sym_db.RegisterMessage(ConnectionResponse)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'serverchat_pb2'
  # @@protoc_insertion_point(class_scope:serverchat.Status)
  })
_sym_db.RegisterMessage(Status)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'serverchat_pb2'
  # @@protoc_insertion_point(class_scope:serverchat.Message)
  })
_sym_db.RegisterMessage(Message)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'serverchat_pb2'
  # @@protoc_insertion_point(class_scope:serverchat.Action)
  })
_sym_db.RegisterMessage(Action)



_SERVERCHAT = _descriptor.ServiceDescriptor(
  name='ServerChat',
  full_name='serverchat.ServerChat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=455,
  serialized_end=734,
  methods=[
  _descriptor.MethodDescriptor(
    name='connect',
    full_name='serverchat.ServerChat.connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTIONREQUEST,
    output_type=_CONNECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disconnect',
    full_name='serverchat.ServerChat.disconnect',
    index=1,
    containing_service=None,
    input_type=_DISCONNECTIONREQUEST,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='send_message',
    full_name='serverchat.ServerChat.send_message',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_chat_stream',
    full_name='serverchat.ServerChat.get_chat_stream',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ACTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERCHAT)

DESCRIPTOR.services_by_name['ServerChat'] = _SERVERCHAT

# @@protoc_insertion_point(module_scope)
